name: Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    env:
      REPO: crazni/express
      PLATFORMS: linux/amd64,linux/arm64

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb
      - name: Log in to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Backend extract metadata (tags, labels)
        id: bemeta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REPO }}
          tags: |
            type=semver,pattern={{version}}
      - name: Backend build and push Docker image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: ./backend
          platforms: ${{ env.PLATFORMS }}
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.REPO }}:latest,${{ steps.bemeta.outputs.tags }}
          labels: ${{ steps.bemeta.outputs.labels }}
